### ISSUE TITLE
[RMP] Retrieval models improvements and fixes

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#458]
- [x] https://github.com/NVIDIA-Merlin/models/pull/398
- [x] https://github.com/NVIDIA-Merlin/models/pull/447
- [x] https://github.com/NVIDIA-Merlin/models/pull/457
- [x] https://github.com/NVIDIA-Merlin/models/pull/464
- [x] https://github.com/NVIDIA-Merlin/models/issues/461
- [x] https://github.com/NVIDIA-Merlin/models/pull/475
- [x] https://github.com/NVIDIA-Merlin/models/pull/488
